name: database
services:
  db:
    image: mariadb:latest
    container_name: database
    restart: always
    environment:
      MYSQL_DATABASE: gait
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
