import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { getUser } from "../auth/actions/verifySession";
import Navigation from "../shared/components/Navigation";

const poppins = Poppins({
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Gait",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getUser();

  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased`}>
        <main className="grid grid-cols-5 h-screen">
          <Navigation role={user.role} user={user} type={user.type} />
          <section className="col-span-4">{children}</section>
        </main>
      </body>
    </html>
  );
}
